version: 1.2
workflows:
 - name: TheiaEuk_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaeuk/wf_theiaeuk_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Cauris_CladeTyper_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaeuk/wf_cauris_cladetyper.wdl
   testParameterFiles:
    - empty.json
 - name: Snippy_Variants_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_snippy_variants.wdl
   testParameterFiles:
    - empty.json
 - name: Snippy_Tree_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_tree.wdl
   testParameterFiles:
    - empty.json
 - name: Nullarbor_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_nullarbor.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_ClearLabs_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_clearlabs.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_ont.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_pe.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Illumina_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_se.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Validate_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_validate.wdl
   testParameterFiles:
    - empty.json
 - name: Mercury_Prep_N_Batch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/mercury/wf_mercury_prep_n_batch.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Augur_Prep_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_theiacov_augur_prep.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Augur_Run_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_theiacov_augur_run.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaCoV_Augur_DistanceTree_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_theiacov_augur_distance_tree.wdl
   testParameterFiles:
    - empty.json
 - name: Pangolin_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_pangolin_update.wdl
   testParameterFiles:
    - empty.json
 - name: VADR_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_vadr_update.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI_Scrub_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_se.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI_Scrub_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_FASTQ_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_fastq.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_Plot_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_plot.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_Dashboard_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_dashboard.wdl
   testParameterFiles:
    - empty.json
 - name: Freyja_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_update.wdl
   testParameterFiles:
    - empty.json
 - name: kSNP3_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_ksnp3.wdl
   testParameterFiles:
    - empty.json
 - name: MashTree_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_mashtree_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: Core_Gene_SNP_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_core_gene_snp.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaProk_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaProk_Illumina_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_se.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaProk_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_fasta.wdl
   testParameterFiles:
    - empty.json
 - name: TheiaProk_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_ont.wdl
   testParameterFiles:
    - empty.json
 - name: Gambit_Query_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_gambit_query.wdl
   testParameterFiles:
    - empty.json
 - name: Kleborate_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kleborate.wdl
   testParameterFiles:
    - empty.json
 - name: SerotypeFinder_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_serotypefinder.wdl
   testParameterFiles:
    - empty.json
 - name: TBProfiler_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_tbprofiler_pe.wdl
   testParameterFiles:
    - empty.json
 - name: TBProfiler_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_tbprofiler_ont.wdl
   testParameterFiles:
    - empty.json
 - name: NCBI-AMRFinderPlus_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_amrfinderplus.wdl
   testParameterFiles:
    - empty.json
 - name: Kraken2_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_pe.wdl
   testParameterFiles:
    - empty.json
 - name: Kraken2_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_se.wdl
   testParameterFiles:
    - empty.json
 - name: RASUSA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_rasusa.wdl
   testParameterFiles:
    - empty.json
