version: 1.2
workflows:
  - name: Terra_2_ENA
    subclass: WDL
    primaryDescriptorPath: /workflows/submission/wf_terra_2_ena.wdl
  - name: freyja_update
    subclass: WDL
    primaryDescriptorPath: /workflows/freyja/wf_freyja_update.wdl
  - name: mercury_prep_n_batch
    subclass: WDL
    primaryDescriptorPath: /workflows/submission/wf_mercury_prep_n_batch.wdl
  - name: amr_search_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_amr_search.wdl
  - name: freyja_fastq
    subclass: WDL
    primaryDescriptorPath: /workflows/freyja/wf_freyja_fastq.wdl
  - name: theiaeuk_ont
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaeuk/wf_theiaeuk_ont.wdl
  - name: pangolin_update
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/updates/wf_pangolin_update.wdl
  - name: snippy_streamline
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_streamline.wdl
  - name: freyja_plot
    subclass: WDL
    primaryDescriptorPath: /workflows/freyja/wf_freyja_plot.wdl
  - name: create_terra_table
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_create_terra_table.wdl
  - name: rasusa_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_rasusa.wdl
  - name: clair3_variants_ont
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_clair3_variants_ont.wdl
  - name: terra_2_bq
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_terra_2_bq.wdl
  - name: gambitcore_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_gambitcore.wdl
  - name: Terra_2_NCBI
    subclass: WDL
    primaryDescriptorPath: /workflows/submission/wf_terra_2_ncbi.wdl
  - name: augur
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_augur.wdl
  - name: cauris_cladetyper
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaeuk/wf_cauris_cladetyper.wdl
  - name: kraken2_pe_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_pe.wdl
  - name: theiaprok_fasta
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_fasta.wdl
  - name: snippy_streamline_fasta
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_streamline_fasta.wdl
  - name: nextclade_batch
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_nextclade_batch.wdl
  - name: theiacov_clearlabs
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_clearlabs.wdl
  - name: core_gene_snp_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_core_gene_snp.wdl
  - name: concatenate_column_content
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/file_handling/wf_concatenate_column.wdl
  - name: fetch_sra_to_fastq
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_sra_fetch.wdl
  - name: tbprofiler_tngs
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_tbprofiler_tngs.wdl
  - name: theiaviral_ont
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaviral/wf_theiaviral_ont.wdl
  - name: theiacov_fasta_batch
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_fasta_batch.wdl
  - name: theiaeuk_illumina_pe
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
  - name: transfer_column_content
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/file_handling/wf_transfer_column.wdl
  - name: freyja_dashboard
    subclass: WDL
    primaryDescriptorPath: /workflows/freyja/wf_freyja_dashboard.wdl
  - name: gambit_query
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_gambit_query.wdl
  - name: usher_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_usher.wdl
  - name: theiameta_illumina_pe
    subclass: WDL
    primaryDescriptorPath: /workflows/theiameta/wf_theiameta_illumina_pe.wdl
  - name: dehost_pe
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_pe.wdl
  - name: Terra_2_GISAID
    subclass: WDL
    primaryDescriptorPath: /workflows/submission/wf_terra_2_gisaid.wdl
  - name: dehost_se
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_se.wdl
  - name: phylocompare
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_phylocompare.wdl
  - name: kraken2_ont_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_ont.wdl
  - name: assembly_fetch
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_assembly_fetch.wdl
  - name: theiacov_fasta
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_fasta.wdl
  - name: mashtree_fasta
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_mashtree_fasta.wdl
  - name: czgenepi_prep
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/wf_czgenepi_prep.wdl
  - name: theiaprok_ont
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_ont.wdl
  - name: theiacov_illumina_se
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_se.wdl
  - name: vadr_update
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/updates/wf_vadr_update.wdl
  - name: shared_variants_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_find_shared_variants.wdl
  - name: ksnp4_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_ksnp4.wdl
  - name: dorado_basecalling
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_dorado_basecalling.wdl
  - name: theiavalidate
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/wf_theiavalidate.wdl
  - name: theiaprok_illumina_pe
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
  - name: ksnp3_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_ksnp3.wdl
  - name: rename_fastq_files
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/file_handling/wf_rename_fastq_files.wdl
  - name: zip_column_content
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/file_handling/wf_zip_column.wdl
  - name: fetch_srr_accession
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_fetch_srr_accession.wdl
  - name: theiacov_illumina_pe
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_pe.wdl
  - name: lyveset_workflow
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_lyveset.wdl
  - name: ont_barcode_concatenation
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_ont_barcode_concatenation.wdl
  - name: amrfinderplus_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_amrfinderplus.wdl
  - name: theiaviral_panel
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaviral/wf_theiaviral_panel.wdl
  - name: augur_prep
    subclass: WDL
    primaryDescriptorPath: /workflows/phylogenetics/wf_augur_prep.wdl
  - name: basespace_fetch
    subclass: WDL
    primaryDescriptorPath: /workflows/utilities/data_import/wf_basespace_fetch.wdl
  - name: theiacov_ont
    subclass: WDL
    primaryDescriptorPath: /workflows/theiacov/wf_theiacov_ont.wdl
  - name: theiaprok_illumina_se
    subclass: WDL
    primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_se.wdl
  - name: kraken2_se_wf
    subclass: WDL
    primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_se.wdl
