version: 1.2
workflows:
 - name: TheiaEuk_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaeuk/wf_theiaeuk_illumina_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Cauris_CladeTyper_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaeuk/wf_cauris_cladetyper.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Snippy_Variants_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_snippy_variants.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Snippy_Tree_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_tree.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Nullarbor_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_nullarbor.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_ClearLabs_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_clearlabs.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_ont.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_Illumina_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_illumina_se.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_fasta.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaCoV_FASTA_Batch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/wf_theiacov_fasta_batch.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Mercury_Prep_N_Batch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/submission/wf_mercury_prep_n_batch.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Terra_2_NCBI_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/submission/wf_terra_2_ncbi.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Augur_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_augur.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Augur_Prep_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_augur_prep.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Pangolin_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_pangolin_update.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: VADR_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_vadr_update.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: NCBI_Scrub_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_se.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: NCBI_Scrub_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiacov/updates/wf_ncbi_scrub_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Freyja_FASTQ_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_fastq.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Freyja_Plot_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_plot.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Freyja_Dashboard_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_dashboard.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Freyja_Update_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/freyja/wf_freyja_update.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: kSNP3_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_ksnp3.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: MashTree_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_mashtree_fasta.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Core_Gene_SNP_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_core_gene_snp.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaProk_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaProk_Illumina_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_illumina_se.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaProk_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_fasta.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaProk_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiaprok/wf_theiaprok_ont.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Gambit_Query_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_gambit_query.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: NCBI-AMRFinderPlus_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_amrfinderplus.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Kraken2_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Kraken2_SE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_se.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Kraken2_ONT_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_kraken2_ont.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: RASUSA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_rasusa.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: BaseSpace_Fetch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_basespace_fetch.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: SRA_Fetch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_sra_fetch.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Terra_2_BQ_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_terra_2_bq.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Fetch_SRR_Accession_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_fetch_srr_accession.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Concatenate_Column_Content_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/file_handling/wf_concatenate_column.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Find_Shared_Variants_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_find_shared_variants.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Transfer_Column_Content_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/file_handling/wf_transfer_column.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Zip_Column_Content_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/file_handling/wf_zip_column.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Lyve_SET_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_lyveset.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaMeta_Illumina_PE_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/theiameta/wf_theiameta_illumina_pe.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Snippy_Streamline_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_streamline.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Assembly_Fetch_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_assembly_fetch.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TheiaValidate_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_theiavalidate.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Samples_to_Ref_Tree_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_nextclade_addToRefTree.wdl
 - name: Terra_2_GISAID_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/submission/wf_terra_2_gisaid.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Usher_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_usher.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: CZGenEpi_Prep_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/wf_czgenepi_prep.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: TBProfiler_tNGS_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_tbprofiler_tngs.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Rename_FASTQ_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/file_handling/wf_rename_fastq_files.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Gambit_Core_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/standalone_modules/wf_gambitcore.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Create_Terra_Table_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/data_import/wf_create_terra_table.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Snippy_Streamline_FASTA_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/phylogenetics/wf_snippy_streamline_fasta.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: Concatenate_Illumina_Lanes_PHB
   subclass: WDL
   primaryDescriptorPath: /workflows/utilities/file_handling/wf_concatenate_illumina_lanes.wdl
   testParameterFiles:
     - /tests/inputs/empty.json