name: Sprocket Lint

on:
  push:
    branches: [main]
    paths:
      - "tasks/**"
      - "workflows/**"
      - ".github/workflows/sprocket-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "tasks/**"
      - "workflows/**"
      - ".github/workflows/sprocket-lint.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Find changed WDL files
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            wdl:
              - added|modified: "tasks/**/*.wdl"
              - added|modified: "workflows/**/*.wdl"
          list-files: json

      - name: Install latest Sprocket
        if: steps.filter.outputs.wdl == 'true'
        uses: jaxxstorm/action-install-gh-release@v3.0.0
        with:
          repo: stjude-rust-labs/sprocket
          tag: latest
          asset-name: sprocket

      - name: Lint WDL
        if: steps.filter.outputs.wdl == 'true'
        env:
          WDL_FILES: ${{ steps.filter.outputs.wdl_files }}
        run: |
          mapfile -t wdl_files < <(jq -r '.[]' <<< "$WDL_FILES")
          sprocket lint "${wdl_files[@]}"
